image: archlinux
secrets:
- ef99914b-29db-4c22-a2e5-91213b37cc27
packages:
  - emacs-nox
oauth: pages.sr.ht/PAGES:RW
sources:
  - git@git.sr.ht:~khaled_mustafa/my-site
environment:
  site: khaled_mustafa.srht.site
tasks:
  - build: |
      # Generate site files
      cd my-site
      ./build.sh

      # Bundle the site
      cd public
      tar -czf /home/build/html.tar.gz .
  - upload: |
      tar -ztvf html.tar.gz
      acurl --fail-with-body https://pages.sr.ht/publish/$site -Fcontent=@html.tar.gz
