#+title: About Me

#+begin_quote
يا ابن آدم، إنما أنت أيام، كلما ذهب يوم ذهب بعضك. - الحسن البصري
#+end_quote

* Welcome!
I'm Khaled Mustafa—a technical educator, embedded software engineer, and electronics enthusiast.

I believe in lifelong learning and the power of technology to transform lives. My passion lies in teaching and building.

* What You'll Find Here
This is my little corner of the internet!

Once in a while, I write about the things that I am passionate about, including technology, Linux,low level software and personal insights. My goal is to share my views and experiences on these topics, and help inform others who are interested in learning more.

Thanks for stopping by! I hope you enjoy reading my articles and find them useful.

* Let’s connect!
I’d love to hear from you! Whether you’re curious about my work, seeking collaboration, or just want to chat, feel free to reach out:
- [[https://www.linkedin.com/in/khaled-mustafa/][LinkedIn]]
- [[mailto:khaled.mustafa.elsayed@outlook.com][Email]]

* How This Site Was Made
Crafted with care using the power of Emacs. [[file:about-site.org][Learn more]] about the tools and processes behind the scenes.
